global:

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'combined-receiver' # Default receiver

receivers:
  - name: 'combined-receiver'
    telegram_configs:
      - bot_token: "##########:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        chat_id: 1183078434               
        send_resolved: true

